fumiwaste/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'


urlpatterns = [
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

fumiwaste/articles/urls.py
from django.urls import path
from .import views

app_name = 'articles'

urlpatterns = [
    path('',views.article_list, name='list'),
    path('create', views.article_create, name='create'),
    path('<slug:slug>/',views.article_details, name='details'),
]

fumiwaste/fumiwaste/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('about/',views.about),
    path('',views.home),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

fumiwaste/accounts/models.py
from django.db import models

# Create your models here.

fumiwaste/articles/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    # add author later

    def __str__(self):
        return self.title
    

    def snippet(self):
        return self.body[:150] + "..."
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)  # Automatically create a URL-safe slug
        super().save(*args, **kwargs)

fumiwaste/articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

fumiwaste/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
 
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html',{'userform': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
       form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form': form})


def logout_view(request):
    if (request.method == 'POST'):
        logout(request)
        # print('user logged out succesfully')
        return redirect('articles:list')

fumiwaste/articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms


# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_details(request,slug):
    print({slug})
    # return HttpResponse( {slug})
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html', {'article': article})
@login_required(login_url='/accounts/login')
def article_create(request):
    if (request.method == 'POST'):
        form = forms.CreateArticle(request.POST, request.FILES)
        # save form to db
        return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form })

fumiwaste/fumiwaste/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(req):
   return render(req, 'Home.html')
   # return HttpResponse("home")


def about(req):
   return render(req, 'About.html')
   # return HttpResponse("about")

fumiwaste/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>LOGIN</h1>
<form action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
    <input type="hidden" name="next" value='{{request.GET.next}}'>

    {% endif %}
    <input type="submit" value="Login">

</form>

{% endblock%}

fumiwaste/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Signup</h1>
<form action="/accounts/signup" method="post">
    {% csrf_token %}
    {{userform}}
    <input type="submit" value="Signup">

</form>

{% endblock%}

fumiwaste/articles/templates/articles/article_create.html
{% extends 'base.html' %}

<div class="wrapper">
{% block content %}
<h1>Create Content</h1>
<form action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
  <button type="submit" value="create">Create</button>
</form>



{% endblock %}
</div>

fumiwaste/articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="article">
    <h2>{{article.title}}</h2>
    <img src={{article.thumb.url}} alt="">
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
</div>
{% endblock %}

fumiwaste/articles/templates/articles/article_list.html
{% extends 'base.html' %}


{% block content %}
   <div class="articles">
    {%for article in articles%}
    <div class="article">
        <h2> <a href="{%url 'articles:details' slug=article.slug%}">{{article.title}}</a></h2>
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
    </div>
    {% endfor %}
   </div>
{% endblock %}

fumiwaste/articles/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Article List</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}">
</head>
<body>
    <nav>
        <ul>
            <li>
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
        </ul>
    </nav>
    <div class="wrapper">
{%  block content %}


{% endblock %}
</div>
</body>
</html>

fumiwaste/templates/About.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About Us</h1>
    <p>we are funiwaste</p>
</body>
</html>

fumiwaste/templates/Home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>Homepage</h1>
    <p>welcome to fumiwaste</p>
    
</body>
</html>